---
AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host Drupal on AWS - Creates ElastiCache cache cluster

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Cache Parameters
      Parameters:
        - ElastiCacheNodeType
        - ElastiCacheClusterName
        - ElastiCacheSecurityGroup
        - DataSubnet0
        - DataSubnet1
        - DataSubnet2
    ParameterLabels:
      DataSubnet0:
        default: DataSubnet0
      DataSubnet1:
        default: DataSubnet1
      DataSubnet2:
        default: DataSubnet2
      ElastiCacheClusterName:
        default: Cache Cluster Name
      ElastiCacheNodeType:
        default: Cache Cluster Node Type
      ElastiCacheSecurityGroup:
        default: ElastiCache Security Group

Parameters:
  ParamStackName:
    Type: String
  DataSubnet0:
    Description: Select an existing database subnet for AZ 0.
    Type: AWS::EC2::Subnet::Id
  DataSubnet1:
    Description: Select an existing database subnet for AZ 1.
    Type: AWS::EC2::Subnet::Id
  DataSubnet2:
    Description: Select an existing database subnet for AZ 2.
    Type: AWS::EC2::Subnet::Id
  ElastiCacheClusterName:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: The ElastiCache cluster name. Defaults to the Amazon RDS database name.
    Type: String
  ElastiCacheNodeType:
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
    ConstraintDescription: Must be a valid Amazon ElastiCache node type.
    Default: cache.t2.small
    Description: The Amazon ElastiCache cluster node type.
    Type: String
  ElastiCacheSecurityGroup:
    Description: Select the ElastiCache security group.
    Type: AWS::EC2::SecurityGroup::Id

Conditions:

  MoreThan2AZ:
    !Or [
      !Equals [ !Ref 'AWS::Region', us-gov-east-1 ],
      !Equals [ !Ref 'AWS::Region', us-gov-west-1 ]
    ]

Resources:

  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AZMode: cross-az
      CacheNodeType: !Ref ElastiCacheNodeType
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      ClusterName: !Join [ '-', [ !Ref ElastiCacheClusterName, !Ref ParamStackName ] ]
      Engine: memcached
      NumCacheNodes:
        !If [
          MoreThan2AZ,
          3,
          2
        ]
      PreferredAvailabilityZones:
        !If [
          MoreThan2AZ,
          [ !Select [ 0, !GetAZs '' ], !Select [ 1, !GetAZs '' ], !Select [ 2, !GetAZs '' ] ],
          [ !Select [ 0, !GetAZs '' ], !Select [ 1, !GetAZs '' ] ]
        ]
      Tags:
        - Key: Name
          Value: !Join [ '', [ 'Drupal / ', !Ref 'AWS::StackName' ] ]
      VpcSecurityGroupIds:
      - !Ref ElastiCacheSecurityGroup       
  ElastiCacheSubnetGroup: 
    Type: AWS::ElastiCache::SubnetGroup
    Properties: 
      CacheSubnetGroupName: !Join [ '-', [ !Ref ElastiCacheClusterName, SubnetGroup, !Ref ParamStackName ] ]
      Description: ElastiCache Subnet Group for Drupal
      SubnetIds: 
        !If [
          MoreThan2AZ,
          [ !Ref DataSubnet0, !Ref DataSubnet1, !Ref DataSubnet2 ],
          [ !Ref DataSubnet0, !Ref DataSubnet1 ]
        ]
Outputs:
  ElastiCacheClusterEndpointAddress:
    Value: !GetAtt ElastiCacheCluster.ConfigurationEndpoint.Address
